// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class TempUser
{
    public Guid Id { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public string Role { get; set; }

    public string OtpCode { get; set; }

    public DateTime? OtpExpiresAt { get; set; }

    public DateTime? CreatedAt { get; set; }
}